# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Usage
  items:
    - label: 'Customers'
      link: '/usage/customers'
    - label: 'Reservations'
      link: '/usage/reservations'
    - label: 'Taking Payments'
      link: '/usage/payments'
    - label: 'Data Security'
      link: '/usage/security'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: Video Training
      link: /training
    - label: 'Github'
      link: https://github.com/apmcknight/theater-app
