// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheaterApp.Employee.Data;

namespace TheaterApp.Employee.Migrations.Reservation
{
    [DbContext(typeof(ReservationContext))]
    [Migration("20210312000924_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("TheaterApp.Employee.Models.Reservation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AddAnniversaryPackage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AddBirthdayPackage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGroupSale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReservationCustomerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReservationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReservationGuestAlergey")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservationGuestAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReservationGuestNames")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReservationPaymentDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReservationSeatingPreference")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReservationShow")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReservationTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasReservationPrePaid")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Reservation");
                });
#pragma warning restore 612, 618
        }
    }
}
